@ContosoPizza_HostAddress = https://localhost:7084

GET {{ContosoPizza_HostAddress}}/weatherforecast/
Accept: application/json

###
GET {{ContosoPizza_HostAddress}}/pizza/
Accept: application/json

###
GET {{ContosoPizza_HostAddress}}/pizza/1
Accept: application/json

###
GET {{ContosoPizza_HostAddress}}/pizza/5
Accept: application/json

### Create a new pizza
POST {{ContosoPizza_HostAddress}}/pizza/
Content-Type: application/json

{
    "name": "Hawaii",
    "isGlutenFree": false
}

### Update a pizza
PUT {{ContosoPizza_HostAddress}}/pizza/3
Content-Type: application/json

{
    "id": 3,
    "name": "Hawaiian",
    "isGlutenFree": false
}

### Delete a pizza
DELETE {{ContosoPizza_HostAddress}}/pizza/3